name = "At"
badges = ["github-actions/linux.yaml", "github-actions/windows.yaml", "github-actions/osx.yaml", "metacpan"]
module_maker="ModuleBuildTiny"
static_install = "auto"
license = "artistic_2"
markdown_maker = "Pod::Markdown::Github"
readme_from = "lib/At.pod"
abstract_from = "lib/At.pod"
authors_from = "lib/At.pod"

[release]
hooks=[
    'tidyall -a'
]

[no_index]
directory=[
    "t",
    "xt",
    "inc",
    "share",
    "eg",
    "examples",
    "author"
]

[Metadata]
X_No_Archive = 'Yes'
